# BUILD file in my_hello_project/

load("@rules_python//python:defs.bzl", "py_binary")

package(
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "hello_world_app",
    srcs = ["main.py"],
    main = "main.py",
)
